### ISSUE TITLE
Additional metadata proposals from Philip

### ISSUE THREAD

**Issue by kosek** [eu-invoice/ce-config#1]
* In the <meta> I would add some "based upon" or "extends" element, because I will also create a "CIUS-AT-GOV" which will be based on this "CIUS-AT-NAT".
* All the <cardinality> elements should be wrapped in a "<ruleChanges>" element???
* Maybe one root-level element "in-production" (of type boolean) could be added?

**Comment by phax** [comment]
Ad point 2) in an element labeled `<rules-changes>` or so
And potentially point 4) A new element `is-deprecated` (also of type boolean) could be added?

**Comment by kosek** [comment]
Seems that less-then character has been eaten by GitHub. ;-)
But anyway 2) is resolved, I have already added c:rules around rules.

**Comment by kosek** [comment]
Moved to https://github.com/CenPC434/ce-config/issues/1
